### ISSUE TITLE
Help: Can't make a lightning rod

### ISSUE THREAD

**Issue by fistiG** [redy1aye/CopperEquipment#4]
Heya! I was playin' minecraft and I was tryin' to make a lightning rod but it didn't worked. It just crafts a compressed copper. Is it a bug or something?

**Comment by redy1aye** [comment]
I am very sorry for not checking the github for so long.
Yes, this is my mistake and it will be fixed in the next update!
Thanks for the feedback and wait!

**Comment by redy1aye** [comment]
Fixed!
